# Mapping from two-letter country codes to international English names, 
# taken from CLDR (Unicode Common Locale Data Repository) 26.0.1 json files,
COUNTRIES = {u'AC': u'Ascension Island',
             u'AD': u'Andorra',
             u'AE': u'United Arab Emirates',
             u'AF': u'Afghanistan',
             u'AG': u'Antigua and Barbuda',
             u'AI': u'Anguilla',
             u'AL': u'Albania',
             u'AM': u'Armenia',
             u'AN': u'Netherlands Antilles',
             u'AO': u'Angola',
             u'AQ': u'Antarctica',
             u'AR': u'Argentina',
             u'AS': u'American Samoa',
             u'AT': u'Austria',
             u'AU': u'Australia',
             u'AW': u'Aruba',
             u'AX': u'\xc5land Islands',
             u'AZ': u'Azerbaijan',
             u'BA': u'Bosnia and Herzegovina',
             u'BB': u'Barbados',
             u'BD': u'Bangladesh',
             u'BE': u'Belgium',
             u'BF': u'Burkina Faso',
             u'BG': u'Bulgaria',
             u'BH': u'Bahrain',
             u'BI': u'Burundi',
             u'BJ': u'Benin',
             u'BL': u'Saint Barth\xe9lemy',
             u'BM': u'Bermuda',
             u'BN': u'Brunei',
             u'BO': u'Bolivia',
             u'BQ': u'Caribbean Netherlands',
             u'BR': u'Brazil',
             u'BS': u'Bahamas',
             u'BT': u'Bhutan',
             u'BV': u'Bouvet Island',
             u'BW': u'Botswana',
             u'BY': u'Belarus',
             u'BZ': u'Belize',
             u'CA': u'Canada',
             u'CC': u'Cocos (Keeling) Islands',
             u'CD': u'Congo - Kinshasa',
             u'CF': u'Central African Republic',
             u'CG': u'Congo - Brazzaville',
             u'CH': u'Switzerland',
             u'CI': u'C\xf4te d\u2019Ivoire',
             u'CK': u'Cook Islands',
             u'CL': u'Chile',
             u'CM': u'Cameroon',
             u'CN': u'China',
             u'CO': u'Colombia',
             u'CP': u'Clipperton Island',
             u'CR': u'Costa Rica',
             u'CU': u'Cuba',
             u'CV': u'Cape Verde',
             u'CW': u'Cura\xe7ao',
             u'CX': u'Christmas Island',
             u'CY': u'Cyprus',
             u'CZ': u'Czech Republic',
             u'DE': u'Germany',
             u'DG': u'Diego Garcia',
             u'DJ': u'Djibouti',
             u'DK': u'Denmark',
             u'DM': u'Dominica',
             u'DO': u'Dominican Republic',
             u'DZ': u'Algeria',
             u'EA': u'Ceuta and Melilla',
             u'EC': u'Ecuador',
             u'EE': u'Estonia',
             u'EG': u'Egypt',
             u'EH': u'Western Sahara',
             u'ER': u'Eritrea',
             u'ES': u'Spain',
             u'ET': u'Ethiopia',
             u'EU': u'European Union',
             u'FI': u'Finland',
             u'FJ': u'Fiji',
             u'FK': u'Falkland Islands',
             u'FM': u'Micronesia',
             u'FO': u'Faroe Islands',
             u'FR': u'France',
             u'GA': u'Gabon',
             u'GB': u'United Kingdom',
             u'GD': u'Grenada',
             u'GE': u'Georgia',
             u'GF': u'French Guiana',
             u'GG': u'Guernsey',
             u'GH': u'Ghana',
             u'GI': u'Gibraltar',
             u'GL': u'Greenland',
             u'GM': u'Gambia',
             u'GN': u'Guinea',
             u'GP': u'Guadeloupe',
             u'GQ': u'Equatorial Guinea',
             u'GR': u'Greece',
             u'GS': u'South Georgia & South Sandwich Islands',
             u'GT': u'Guatemala',
             u'GU': u'Guam',
             u'GW': u'Guinea-Bissau',
             u'GY': u'Guyana',
             u'HK': u'Hong Kong SAR China',
             u'HM': u'Heard & McDonald Islands',
             u'HN': u'Honduras',
             u'HR': u'Croatia',
             u'HT': u'Haiti',
             u'HU': u'Hungary',
             u'IC': u'Canary Islands',
             u'ID': u'Indonesia',
             u'IE': u'Ireland',
             u'IL': u'Israel',
             u'IM': u'Isle of Man',
             u'IN': u'India',
             u'IO': u'British Indian Ocean Territory',
             u'IQ': u'Iraq',
             u'IR': u'Iran',
             u'IS': u'Iceland',
             u'IT': u'Italy',
             u'JE': u'Jersey',
             u'JM': u'Jamaica',
             u'JO': u'Jordan',
             u'JP': u'Japan',
             u'KE': u'Kenya',
             u'KG': u'Kyrgyzstan',
             u'KH': u'Cambodia',
             u'KI': u'Kiribati',
             u'KM': u'Comoros',
             u'KN': u'Saint Kitts and Nevis',
             u'KP': u'North Korea',
             u'KR': u'South Korea',
             u'KW': u'Kuwait',
             u'KY': u'Cayman Islands',
             u'KZ': u'Kazakhstan',
             u'LA': u'Laos',
             u'LB': u'Lebanon',
             u'LC': u'Saint Lucia',
             u'LI': u'Liechtenstein',
             u'LK': u'Sri Lanka',
             u'LR': u'Liberia',
             u'LS': u'Lesotho',
             u'LT': u'Lithuania',
             u'LU': u'Luxembourg',
             u'LV': u'Latvia',
             u'LY': u'Libya',
             u'MA': u'Morocco',
             u'MC': u'Monaco',
             u'MD': u'Moldova',
             u'ME': u'Montenegro',
             u'MF': u'Saint Martin',
             u'MG': u'Madagascar',
             u'MH': u'Marshall Islands',
             u'MK': u'Macedonia',
             u'ML': u'Mali',
             u'MM': u'Myanmar (Burma)',
             u'MN': u'Mongolia',
             u'MO': u'Macau SAR China',
             u'MP': u'Northern Mariana Islands',
             u'MQ': u'Martinique',
             u'MR': u'Mauritania',
             u'MS': u'Montserrat',
             u'MT': u'Malta',
             u'MU': u'Mauritius',
             u'MV': u'Maldives',
             u'MW': u'Malawi',
             u'MX': u'Mexico',
             u'MY': u'Malaysia',
             u'MZ': u'Mozambique',
             u'NA': u'Namibia',
             u'NC': u'New Caledonia',
             u'NE': u'Niger',
             u'NF': u'Norfolk Island',
             u'NG': u'Nigeria',
             u'NI': u'Nicaragua',
             u'NL': u'Netherlands',
             u'NO': u'Norway',
             u'NP': u'Nepal',
             u'NR': u'Nauru',
             u'NU': u'Niue',
             u'NZ': u'New Zealand',
             u'OM': u'Oman',
             u'PA': u'Panama',
             u'PE': u'Peru',
             u'PF': u'French Polynesia',
             u'PG': u'Papua New Guinea',
             u'PH': u'Philippines',
             u'PK': u'Pakistan',
             u'PL': u'Poland',
             u'PM': u'Saint Pierre and Miquelon',
             u'PN': u'Pitcairn Islands',
             u'PR': u'Puerto Rico',
             u'PS': u'Palestinian Territories',
             u'PT': u'Portugal',
             u'PW': u'Palau',
             u'PY': u'Paraguay',
             u'QA': u'Qatar',
             u'QO': u'Outlying Oceania',
             u'RE': u'R\xe9union',
             u'RO': u'Romania',
             u'RS': u'Serbia',
             u'RU': u'Russia',
             u'RW': u'Rwanda',
             u'SA': u'Saudi Arabia',
             u'SB': u'Solomon Islands',
             u'SC': u'Seychelles',
             u'SD': u'Sudan',
             u'SE': u'Sweden',
             u'SG': u'Singapore',
             u'SH': u'Saint Helena',
             u'SI': u'Slovenia',
             u'SJ': u'Svalbard and Jan Mayen',
             u'SK': u'Slovakia',
             u'SL': u'Sierra Leone',
             u'SM': u'San Marino',
             u'SN': u'Senegal',
             u'SO': u'Somalia',
             u'SR': u'Suriname',
             u'SS': u'South Sudan',
             u'ST': u'S\xe3o Tom\xe9 and Pr\xedncipe',
             u'SV': u'El Salvador',
             u'SX': u'Sint Maarten',
             u'SY': u'Syria',
             u'SZ': u'Swaziland',
             u'TA': u'Tristan da Cunha',
             u'TC': u'Turks and Caicos Islands',
             u'TD': u'Chad',
             u'TF': u'French Southern Territories',
             u'TG': u'Togo',
             u'TH': u'Thailand',
             u'TJ': u'Tajikistan',
             u'TK': u'Tokelau',
             u'TL': u'Timor-Leste',
             u'TM': u'Turkmenistan',
             u'TN': u'Tunisia',
             u'TO': u'Tonga',
             u'TR': u'Turkey',
             u'TT': u'Trinidad and Tobago',
             u'TV': u'Tuvalu',
             u'TW': u'Taiwan',
             u'TZ': u'Tanzania',
             u'UA': u'Ukraine',
             u'UG': u'Uganda',
             u'UM': u'U.S. Outlying Islands',
             u'US': u'United States',
             u'UY': u'Uruguay',
             u'UZ': u'Uzbekistan',
             u'VA': u'Vatican City',
             u'VC': u'St. Vincent & Grenadines',
             u'VE': u'Venezuela',
             u'VG': u'British Virgin Islands',
             u'VI': u'U.S. Virgin Islands',
             u'VN': u'Vietnam',
             u'VU': u'Vanuatu',
             u'WF': u'Wallis and Futuna',
             u'WS': u'Samoa',
             u'XK': u'Kosovo',
             u'YE': u'Yemen',
             u'YT': u'Mayotte',
             u'ZA': u'South Africa',
             u'ZM': u'Zambia',
             u'ZW': u'Zimbabwe',
             u'ZZ': u'Unknown Region'}
